export default [
  {
    name: 'team.member.jack.li.name',
    title: 'team.member.title.ceo',
    intro: 'team.member.jack.li.intro',
    linkedIn: 'https://www.linkedin.com/in/zhichao-jack-li-a5129a31/',
    imageSrc: '/images/group-16.jpg',
  },
  {
    name: 'team.member.christian.gehl.name',
    title: 'team.member.title.cto',
    intro: 'team.member.christian.gehl.intro',
    linkedIn: 'https://www.linkedin.com/in/christiangehl/',
    imageSrc: '/images/group-17.jpg',
  },
  {
    name: 'team.member.toni.qiu.name',
    title: 'team.member.title.managing.director',
    intro: 'team.member.toni.qiu.intro',
    linkedIn: 'https://www.linkedin.com/in/tengqiu/',
    imageSrc: '/images/group-18.jpg',
  },
  {
    name: 'team.member.jasmine.zhang.name',
    title: 'team.member.title.cmo',
    intro: 'team.member.jasmine.zhang.intro',
    linkedIn: 'https://www.linkedin.com/in/jingqi-zhang-582bb783',
    imageSrc: '/images/group-20.jpg',
  },
  {
    name: 'team.member.qin.liwen.name',
    title: 'team.member.title.cco',
    intro: 'team.member.qin.liwen.intro',
    linkedIn: 'https://www.linkedin.com/in/liwen-qin-96260815/',
    imageSrc: '/images/Liwen-150x150.jpg',
  },
  {
    linkedIn: 'https://www.linkedin.com/in/kierandold/',
    name: 'team.member.ciarandold.name',
    title: 'team.member.title.ux.uidesigner',
    intro: 'team.member.ciarandold.intro',
    imageSrc: '/images/ciaranD.jpg',
  },
  {
    linkedIn: 'https://www.linkedin.com/in/cdbaibai/',
    name: 'team.member.jianiyu.name',
    title: 'team.member.title.projectmanager',
    intro: 'team.member.jianiyu.intro',
    imageSrc: '/images/Jiani.jpg',
  },
  {
    linkedIn: 'https://www.linkedin.com/in/seunghunsunmoonlee/',
    name: 'team.member.seunghun.name',
    title: 'team.member.title.fullstack',
    intro: 'team.member.seunghun.intro',
    imageSrc: '/images/Seunghun-Lee.jpg',
  },
  {
    linkedIn: 'https://www.linkedin.com/in/zongxiong-chen-538043ab/',
    name: 'team.member.zongxiong.name',
    title: 'team.member.title.backendarch',
    intro: 'team.member.zongxiong.intro',
    imageSrc: '/images/Zongxiong.jpg',
  },
  {
    linkedIn: 'https://www.linkedin.com/in/pei-zhang-25920b155/',
    name: 'team.member.peizhang.name',
    title: 'team.member.title.bcloudengineer',
    intro: 'team.member.peizhang.intro',
    imageSrc: '/images/PeiZhang.jpg',
  },
  {
    linkedIn: 'https://www.linkedin.com/in/konrad-rieck-58528015/',
    name: 'team.member.prof.dr.konradrieck.name',
    title: 'team.member.title.scientificadvisor',
    intro: 'team.member.prof.dr.konradrieck.intro',
    imageSrc: '/images/KonradRieck-150x150.jpg',
  },
  {
    linkedIn: 'https://www.linkedin.com/in/lorenz-lorenz-meyer-006304b3/',
    name: 'team.member.prof.dr.lorenz-meyer.name',
    title: 'team.member.title.media.pradvisor',
    intro: 'team.member.prof.dr.lorenz-meyer.intro',
    imageSrc: '/images/Lorenz-Meyer-150x150.jpg',
  },
  {
    linkedIn: 'https://www.linkedin.com/in/renegerstenberger/',
    name: 'team.member.renégerstenberger.name',
    title: 'team.member.title.datasecurityadvisor',
    intro: 'team.member.renégerstenberger.intro',
    imageSrc: '/images/Rene-150x150.jpg',
  },
  {
    linkedIn: 'https://www.linkedin.com/in/simonschwerin/',
    name: 'team.member.simonschwerin.name',
    title: 'team.member.title.blockchainadvisor',
    intro: 'team.member.simonschwerin.intro',
    imageSrc: '/images/simon-150x150.png',
  },
  {
    linkedIn: 'https://de.linkedin.com/in/fuesun',
    name: 'team.member.fuesunwehrmann.name',
    title: 'team.member.title.engineeringadvisor',
    intro: 'team.member.fuesunwehrmann.intro',
    imageSrc: '/images/Fuesun-Wehrmann-Zanox-150x150.jpeg',
  },
  {
    linkedIn: 'https://www.linkedin.com/in/steven-karch-2857241/',
    name: 'team.member.stevenkarch.name',
    title: 'team.member.title.blockchainadvisor',
    intro: 'team.member.stevenkarch.intro',
    imageSrc: '/images/StevenKrach-300x300.jpg',
  },
  {
    linkedIn: 'https://www.linkedin.com/in/ran-wang-036456b/',
    name: 'team.member.ranwang.name',
    title: 'team.member.title.gamepublishingadvisor',
    intro: 'team.member.ranwang.intro',
    imageSrc: '/images/Ran.Wang_-150x150.png',
  },
  {
    linkedIn: 'https://www.linkedin.com/in/yun-cao-34400b59/',
    name: 'team.member.yuncao.name',
    title: 'team.member.title.game.marketingadvisor',
    intro: 'team.member.yuncao.intro',
    imageSrc: '/images/YunCao-1-150x150.jpg',
  },
  {
    linkedIn: 'https://www.linkedin.com/in/davydeh/',
    name: 'team.member.davidespinosa.name',
    title: 'team.member.title.technicalsolutionsadvisor',
    intro: 'team.member.davidespinosa.intro',
    imageSrc: '/images/David_Espinosa-150x150.jpg',
  },
  {
    linkedIn: 'https://www.linkedin.com/in/rasmus-giesel-a1048b1a/',
    name: 'team.member.rasmusgiesel.name',
    title: 'team.member.title.brandingandcreativeadvisor',
    intro: 'team.member.rasmusgiesel.intro',
    imageSrc: '/images/RasmusGiesel-300x300.jpg',
  },
  {
    linkedIn: 'https://www.linkedin.com/in/sandromoscogiuri',
    name: 'team.member.sandromoscogiuri.name',
    title: 'team.member.title.artadvisor',
    intro: 'team.member.sandromoscogiuri.intro',
    imageSrc: '/images/group-22.jpg',
  },
  {
    linkedIn: 'https://www.linkedin.com/in/maurus-radelow-1683b443/',
    name: 'team.member.maurusradelow.name',
    title: 'team.member.title.cyber.informationsecurityadvisor',
    intro: 'team.member.maurusradelow.intro',
    imageSrc: '/images/Maurus_Radelow-150x150.jpg',
  },
  {
    linkedIn: 'https://www.linkedin.com/in/ying-guo-16b3796/',
    name: 'team.member.yingguo.name',
    title: 'team.member.title.marketingandsalesadvisor',
    intro: 'team.member.yingguo.intro',
    imageSrc: '/images/YingGuo-150x150.jpg',
  },
  {
    linkedIn: 'https://www.linkedin.com/in/zeta-zhu-679a301a/',
    name: 'team.member.zetazhu.name',
    title: 'team.member.title.marketingadvisor',
    intro: 'team.member.zetazhu.intro',
    imageSrc: '/images/Zeta_Zhu-150x150.jpg',
  },
]
